name: frontend CI/CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/frontend
  NAMESPACE: default
  KUBECONFIG: /etc/kubernetes/admin.conf   # ← لا نحتاج secret

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}   # أو PASSWORD إن كنت استخدمته
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build & Push image
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE_REPO:$TAG .
          docker push $IMAGE_REPO:$TAG
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Apply manifests
        run: kubectl -n $NAMESPACE apply -f k8s/frontend.yaml

      - name: Update image & rollout
        run: |
          kubectl -n $NAMESPACE set image deploy/frontend web=$IMAGE_REPO:${TAG}
          kubectl -n $NAMESPACE rollout status deploy/frontend
